// Autogenerated code using 
// https://docs.nethereum.com/en/latest/nethereum-codegen-vscodesolidity/

using System;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Numerics;
using Nethereum.Hex.HexTypes;
using Nethereum.ABI.FunctionEncoding.Attributes;
using Nethereum.RPC.Eth.DTOs;
using Nethereum.Contracts.CQS;
using Nethereum.Contracts;
using System.Threading;

namespace UnityPassportDemo {

    public partial class UnityImmutableCheckDeployment : UnityImmutableCheckDeploymentBase
    {
        public UnityImmutableCheckDeployment() : base(BYTECODE) { }
        public UnityImmutableCheckDeployment(string byteCode) : base(byteCode) { }
    }

    public class UnityImmutableCheckDeploymentBase : ContractDeploymentMessage
    {
        public static string BYTECODE = "608080604052346013576096908160188239f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c9081633fa4f2451460495750635524107714602f575f80fd5b3460455760203660031901126045576004355f55005b5f80fd5b346045575f3660031901126045576020905f548152f3fea2646970667358221220c4e11ee18656a2e6151931324605f842b1726201c7f2ad14a6b2b0ba7ec3d45764736f6c634300081e0033";
        public UnityImmutableCheckDeploymentBase() : base(BYTECODE) { }
        public UnityImmutableCheckDeploymentBase(string byteCode) : base(byteCode) { }

    }

    public partial class SetValueFunction : SetValueFunctionBase { }

    [Function("setValue")]
    public class SetValueFunctionBase : FunctionMessage
    {
        [Parameter("uint256", "_value", 1)]
        public virtual BigInteger Value { get; set; }
    }

    public partial class ValueFunction : ValueFunctionBase { }

    [Function("value", "uint256")]
    public class ValueFunctionBase : FunctionMessage
    {

    }

    public partial class ValueSetEventDTO : ValueSetEventDTOBase { }

    [Event("ValueSet")]
    public class ValueSetEventDTOBase : IEventDTO
    {
        [Parameter("uint256", "_value", 1, false )]
        public virtual BigInteger Value { get; set; }
    }



    public partial class ValueOutputDTO : ValueOutputDTOBase { }

    [FunctionOutput]
    public class ValueOutputDTOBase : IFunctionOutputDTO 
    {
        [Parameter("uint256", "", 1)]
        public virtual BigInteger ReturnValue1 { get; set; }
    }
}
